# file: myshell.c
# author: Ben Guiden
# student number: 19310046
# email: ben.guiden2@mail.dcu.ie
#
# I have read and understood the DCU Academic Integrity and Plagiarism Policy. All work is my own unless indicated otherwise.
#
# ca216/myshell

myshell: myshell.c utility.c myshell.h
	gcc -Wall myshell.c utility.c -o ../bin/myshell
